// Lista completa de países con su código de marcación (para el selector de WhatsApp).
// La bandera se genera desde el código ISO-2 con flagOf() — así no hay que escribir 200 emojis.

export type Country = { c: string; n: string; d: string }; // c = ISO-2, n = nombre, d = código (+xx)

/** Convierte un ISO-2 (ej. "DO") en su emoji de bandera. */
export function flagOf(iso2: string): string {
  return (iso2 || "")
    .toUpperCase()
    .replace(/./g, (ch) => String.fromCodePoint(127397 + ch.charCodeAt(0)));
}

export const COUNTRIES: Country[] = [
  { c: "AF", n: "Afganistán", d: "+93" },
  { c: "AL", n: "Albania", d: "+355" },
  { c: "DE", n: "Alemania", d: "+49" },
  { c: "AD", n: "Andorra", d: "+376" },
  { c: "AO", n: "Angola", d: "+244" },
  { c: "AI", n: "Anguila", d: "+1264" },
  { c: "AG", n: "Antigua y Barbuda", d: "+1268" },
  { c: "SA", n: "Arabia Saudita", d: "+966" },
  { c: "DZ", n: "Argelia", d: "+213" },
  { c: "AR", n: "Argentina", d: "+54" },
  { c: "AM", n: "Armenia", d: "+374" },
  { c: "AW", n: "Aruba", d: "+297" },
  { c: "AU", n: "Australia", d: "+61" },
  { c: "AT", n: "Austria", d: "+43" },
  { c: "AZ", n: "Azerbaiyán", d: "+994" },
  { c: "BS", n: "Bahamas", d: "+1242" },
  { c: "BH", n: "Baréin", d: "+973" },
  { c: "BD", n: "Bangladés", d: "+880" },
  { c: "BB", n: "Barbados", d: "+1246" },
  { c: "BE", n: "Bélgica", d: "+32" },
  { c: "BZ", n: "Belice", d: "+501" },
  { c: "BJ", n: "Benín", d: "+229" },
  { c: "BM", n: "Bermudas", d: "+1441" },
  { c: "BY", n: "Bielorrusia", d: "+375" },
  { c: "MM", n: "Birmania (Myanmar)", d: "+95" },
  { c: "BO", n: "Bolivia", d: "+591" },
  { c: "BA", n: "Bosnia y Herzegovina", d: "+387" },
  { c: "BW", n: "Botsuana", d: "+267" },
  { c: "BR", n: "Brasil", d: "+55" },
  { c: "BN", n: "Brunéi", d: "+673" },
  { c: "BG", n: "Bulgaria", d: "+359" },
  { c: "BF", n: "Burkina Faso", d: "+226" },
  { c: "BI", n: "Burundi", d: "+257" },
  { c: "BT", n: "Bután", d: "+975" },
  { c: "CV", n: "Cabo Verde", d: "+238" },
  { c: "KH", n: "Camboya", d: "+855" },
  { c: "CM", n: "Camerún", d: "+237" },
  { c: "CA", n: "Canadá", d: "+1" },
  { c: "QA", n: "Catar", d: "+974" },
  { c: "TD", n: "Chad", d: "+235" },
  { c: "CL", n: "Chile", d: "+56" },
  { c: "CN", n: "China", d: "+86" },
  { c: "CY", n: "Chipre", d: "+357" },
  { c: "VA", n: "Ciudad del Vaticano", d: "+379" },
  { c: "CO", n: "Colombia", d: "+57" },
  { c: "KM", n: "Comoras", d: "+269" },
  { c: "CG", n: "Congo", d: "+242" },
  { c: "CD", n: "Congo (Rep. Dem.)", d: "+243" },
  { c: "KP", n: "Corea del Norte", d: "+850" },
  { c: "KR", n: "Corea del Sur", d: "+82" },
  { c: "CI", n: "Costa de Marfil", d: "+225" },
  { c: "CR", n: "Costa Rica", d: "+506" },
  { c: "HR", n: "Croacia", d: "+385" },
  { c: "CU", n: "Cuba", d: "+53" },
  { c: "CW", n: "Curazao", d: "+599" },
  { c: "DK", n: "Dinamarca", d: "+45" },
  { c: "DM", n: "Dominica", d: "+1767" },
  { c: "EC", n: "Ecuador", d: "+593" },
  { c: "EG", n: "Egipto", d: "+20" },
  { c: "SV", n: "El Salvador", d: "+503" },
  { c: "AE", n: "Emiratos Árabes Unidos", d: "+971" },
  { c: "ER", n: "Eritrea", d: "+291" },
  { c: "SK", n: "Eslovaquia", d: "+421" },
  { c: "SI", n: "Eslovenia", d: "+386" },
  { c: "ES", n: "España", d: "+34" },
  { c: "US", n: "Estados Unidos", d: "+1" },
  { c: "EE", n: "Estonia", d: "+372" },
  { c: "SZ", n: "Esuatini", d: "+268" },
  { c: "ET", n: "Etiopía", d: "+251" },
  { c: "PH", n: "Filipinas", d: "+63" },
  { c: "FI", n: "Finlandia", d: "+358" },
  { c: "FJ", n: "Fiyi", d: "+679" },
  { c: "FR", n: "Francia", d: "+33" },
  { c: "GA", n: "Gabón", d: "+241" },
  { c: "GM", n: "Gambia", d: "+220" },
  { c: "GE", n: "Georgia", d: "+995" },
  { c: "GH", n: "Ghana", d: "+233" },
  { c: "GI", n: "Gibraltar", d: "+350" },
  { c: "GD", n: "Granada", d: "+1473" },
  { c: "GR", n: "Grecia", d: "+30" },
  { c: "GL", n: "Groenlandia", d: "+299" },
  { c: "GP", n: "Guadalupe", d: "+590" },
  { c: "GU", n: "Guam", d: "+1671" },
  { c: "GT", n: "Guatemala", d: "+502" },
  { c: "GF", n: "Guayana Francesa", d: "+594" },
  { c: "GN", n: "Guinea", d: "+224" },
  { c: "GQ", n: "Guinea Ecuatorial", d: "+240" },
  { c: "GW", n: "Guinea-Bisáu", d: "+245" },
  { c: "GY", n: "Guyana", d: "+592" },
  { c: "HT", n: "Haití", d: "+509" },
  { c: "HN", n: "Honduras", d: "+504" },
  { c: "HK", n: "Hong Kong", d: "+852" },
  { c: "HU", n: "Hungría", d: "+36" },
  { c: "IN", n: "India", d: "+91" },
  { c: "ID", n: "Indonesia", d: "+62" },
  { c: "IQ", n: "Irak", d: "+964" },
  { c: "IR", n: "Irán", d: "+98" },
  { c: "IE", n: "Irlanda", d: "+353" },
  { c: "IM", n: "Isla de Man", d: "+44" },
  { c: "IS", n: "Islandia", d: "+354" },
  { c: "KY", n: "Islas Caimán", d: "+1345" },
  { c: "CK", n: "Islas Cook", d: "+682" },
  { c: "FO", n: "Islas Feroe", d: "+298" },
  { c: "FK", n: "Islas Malvinas", d: "+500" },
  { c: "MH", n: "Islas Marshall", d: "+692" },
  { c: "SB", n: "Islas Salomón", d: "+677" },
  { c: "VG", n: "Islas Vírgenes Británicas", d: "+1284" },
  { c: "VI", n: "Islas Vírgenes (EE. UU.)", d: "+1340" },
  { c: "IL", n: "Israel", d: "+972" },
  { c: "IT", n: "Italia", d: "+39" },
  { c: "JM", n: "Jamaica", d: "+1876" },
  { c: "JP", n: "Japón", d: "+81" },
  { c: "JO", n: "Jordania", d: "+962" },
  { c: "KZ", n: "Kazajistán", d: "+7" },
  { c: "KE", n: "Kenia", d: "+254" },
  { c: "KG", n: "Kirguistán", d: "+996" },
  { c: "KI", n: "Kiribati", d: "+686" },
  { c: "XK", n: "Kosovo", d: "+383" },
  { c: "KW", n: "Kuwait", d: "+965" },
  { c: "LA", n: "Laos", d: "+856" },
  { c: "LS", n: "Lesoto", d: "+266" },
  { c: "LV", n: "Letonia", d: "+371" },
  { c: "LB", n: "Líbano", d: "+961" },
  { c: "LR", n: "Liberia", d: "+231" },
  { c: "LY", n: "Libia", d: "+218" },
  { c: "LI", n: "Liechtenstein", d: "+423" },
  { c: "LT", n: "Lituania", d: "+370" },
  { c: "LU", n: "Luxemburgo", d: "+352" },
  { c: "MO", n: "Macao", d: "+853" },
  { c: "MK", n: "Macedonia del Norte", d: "+389" },
  { c: "MG", n: "Madagascar", d: "+261" },
  { c: "MY", n: "Malasia", d: "+60" },
  { c: "MW", n: "Malaui", d: "+265" },
  { c: "MV", n: "Maldivas", d: "+960" },
  { c: "ML", n: "Malí", d: "+223" },
  { c: "MT", n: "Malta", d: "+356" },
  { c: "MA", n: "Marruecos", d: "+212" },
  { c: "MQ", n: "Martinica", d: "+596" },
  { c: "MU", n: "Mauricio", d: "+230" },
  { c: "MR", n: "Mauritania", d: "+222" },
  { c: "MX", n: "México", d: "+52" },
  { c: "FM", n: "Micronesia", d: "+691" },
  { c: "MD", n: "Moldavia", d: "+373" },
  { c: "MC", n: "Mónaco", d: "+377" },
  { c: "MN", n: "Mongolia", d: "+976" },
  { c: "ME", n: "Montenegro", d: "+382" },
  { c: "MS", n: "Montserrat", d: "+1664" },
  { c: "MZ", n: "Mozambique", d: "+258" },
  { c: "NA", n: "Namibia", d: "+264" },
  { c: "NR", n: "Nauru", d: "+674" },
  { c: "NP", n: "Nepal", d: "+977" },
  { c: "NI", n: "Nicaragua", d: "+505" },
  { c: "NE", n: "Níger", d: "+227" },
  { c: "NG", n: "Nigeria", d: "+234" },
  { c: "NO", n: "Noruega", d: "+47" },
  { c: "NC", n: "Nueva Caledonia", d: "+687" },
  { c: "NZ", n: "Nueva Zelanda", d: "+64" },
  { c: "OM", n: "Omán", d: "+968" },
  { c: "NL", n: "Países Bajos", d: "+31" },
  { c: "PK", n: "Pakistán", d: "+92" },
  { c: "PW", n: "Palaos", d: "+680" },
  { c: "PS", n: "Palestina", d: "+970" },
  { c: "PA", n: "Panamá", d: "+507" },
  { c: "PG", n: "Papúa Nueva Guinea", d: "+675" },
  { c: "PY", n: "Paraguay", d: "+595" },
  { c: "PE", n: "Perú", d: "+51" },
  { c: "PF", n: "Polinesia Francesa", d: "+689" },
  { c: "PL", n: "Polonia", d: "+48" },
  { c: "PT", n: "Portugal", d: "+351" },
  { c: "PR", n: "Puerto Rico", d: "+1" },
  { c: "GB", n: "Reino Unido", d: "+44" },
  { c: "CF", n: "República Centroafricana", d: "+236" },
  { c: "CZ", n: "República Checa", d: "+420" },
  // RD tiene tres códigos de área y los tres están en uso. Con "+1" a secas el
  // alumno tenía que acordarse de escribirlo; así lo elige y no se equivoca.
  { c: "DO", n: "República Dominicana (809)", d: "+1809" },
  { c: "DO", n: "República Dominicana (829)", d: "+1829" },
  { c: "DO", n: "República Dominicana (849)", d: "+1849" },
  { c: "RE", n: "Reunión", d: "+262" },
  { c: "RW", n: "Ruanda", d: "+250" },
  { c: "RO", n: "Rumanía", d: "+40" },
  { c: "RU", n: "Rusia", d: "+7" },
  { c: "EH", n: "Sahara Occidental", d: "+212" },
  { c: "WS", n: "Samoa", d: "+685" },
  { c: "KN", n: "San Cristóbal y Nieves", d: "+1869" },
  { c: "SM", n: "San Marino", d: "+378" },
  { c: "MF", n: "San Martín", d: "+590" },
  { c: "VC", n: "San Vicente y las Granadinas", d: "+1784" },
  { c: "LC", n: "Santa Lucía", d: "+1758" },
  { c: "ST", n: "Santo Tomé y Príncipe", d: "+239" },
  { c: "SN", n: "Senegal", d: "+221" },
  { c: "RS", n: "Serbia", d: "+381" },
  { c: "SC", n: "Seychelles", d: "+248" },
  { c: "SL", n: "Sierra Leona", d: "+232" },
  { c: "SG", n: "Singapur", d: "+65" },
  { c: "SY", n: "Siria", d: "+963" },
  { c: "SO", n: "Somalia", d: "+252" },
  { c: "LK", n: "Sri Lanka", d: "+94" },
  { c: "ZA", n: "Sudáfrica", d: "+27" },
  { c: "SD", n: "Sudán", d: "+249" },
  { c: "SS", n: "Sudán del Sur", d: "+211" },
  { c: "SE", n: "Suecia", d: "+46" },
  { c: "CH", n: "Suiza", d: "+41" },
  { c: "SR", n: "Surinam", d: "+597" },
  { c: "TH", n: "Tailandia", d: "+66" },
  { c: "TW", n: "Taiwán", d: "+886" },
  { c: "TZ", n: "Tanzania", d: "+255" },
  { c: "TJ", n: "Tayikistán", d: "+992" },
  { c: "TL", n: "Timor Oriental", d: "+670" },
  { c: "TG", n: "Togo", d: "+228" },
  { c: "TO", n: "Tonga", d: "+676" },
  { c: "TT", n: "Trinidad y Tobago", d: "+1868" },
  { c: "TN", n: "Túnez", d: "+216" },
  { c: "TM", n: "Turkmenistán", d: "+993" },
  { c: "TR", n: "Turquía", d: "+90" },
  { c: "TV", n: "Tuvalu", d: "+688" },
  { c: "UA", n: "Ucrania", d: "+380" },
  { c: "UG", n: "Uganda", d: "+256" },
  { c: "UY", n: "Uruguay", d: "+598" },
  { c: "UZ", n: "Uzbekistán", d: "+998" },
  { c: "VU", n: "Vanuatu", d: "+678" },
  { c: "VE", n: "Venezuela", d: "+58" },
  { c: "VN", n: "Vietnam", d: "+84" },
  { c: "YE", n: "Yemen", d: "+967" },
  { c: "DJ", n: "Yibuti", d: "+253" },
  { c: "ZM", n: "Zambia", d: "+260" },
  { c: "ZW", n: "Zimbabue", d: "+263" },
];


/**
 * Une el prefijo del país con lo que escribió la persona, en formato E.164.
 *
 * Existe porque mucha gente escribe su número completo con el código de área
 * ("8091234567") aunque ya lo haya elegido en la lista. Concatenar a ciegas
 * daba "+18098091234567", un número inválido que rompía el WhatsApp.
 *
 * - Si lo escrito ya empieza por el prefijo elegido, no se duplica.
 * - En RD, si eligió 809 pero escribió un 829/849, manda lo que escribió:
 *   el número real pesa más que la opción de la lista.
 */
export function buildPhoneE164(dial: string, raw: string): string {
  const digits = (raw || "").replace(/\D/g, "");
  const dialDigits = (dial || "").replace(/\D/g, "");
  if (!digits) return "";
  if (digits.startsWith(dialDigits)) return `+${digits}`;
  if (dialDigits.startsWith("1") && dialDigits.length === 4 && digits.length === 10) {
    return `+1${digits}`;
  }
  return `+${dialDigits}${digits}`;
}
