"use strict";(()=>{var e={};e.id=5409,e.ids=[5409],e.modules={20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},84770:e=>{e.exports=require("crypto")},65701:(e,a,t)=>{t.r(a),t.d(a,{originalPathname:()=>b,patchFetch:()=>v,requestAsyncStorage:()=>f,routeModule:()=>x,serverHooks:()=>y,staticGenerationAsyncStorage:()=>h});var r={};t.r(r),t.d(r,{POST:()=>m,dynamic:()=>g});var i=t(49303),n=t(88716),o=t(60670),s=t(87070),p=t(52663),d=t(42023),l=t.n(d),c=t(84770),u=t.n(c);let g="force-dynamic";async function m(e){try{let{email:a,firstName:t,lastName:r,whatsappNumber:i}=await e.json();if(!a||!t||!r||!i)return s.NextResponse.json({error:"Todos los campos son obligatorios: nombre, apellido, email y WhatsApp"},{status:400});if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(a))return s.NextResponse.json({error:"El formato del email no es v\xe1lido"},{status:400});if(!/^\+?[1-9]\d{7,14}$/.test(i.replace(/[\s-]/g,"")))return s.NextResponse.json({error:"El n\xfamero de WhatsApp debe tener formato internacional (ej: +521234567890)"},{status:400});if(await p._.user.findUnique({where:{email:a.toLowerCase()}}))return s.NextResponse.json({error:"Ya existe una cuenta con este email"},{status:400});let n=u().randomBytes(4).toString("hex").toUpperCase(),o=await l().hash(n,12),d=u().randomBytes(32).toString("hex"),c=new Date(Date.now()+864e5),g=await p._.user.create({data:{email:a.toLowerCase(),password:o,firstName:t,lastName:r,whatsappNumber:i.replace(/[\s-]/g,""),verificationToken:d,tokenExpiry:c}});await p._.lead.create({data:{email:a.toLowerCase(),firstName:t,lastName:r,whatsappNumber:i.replace(/[\s-]/g,""),source:"registro",status:"registered"}});let m=process.env.NEXTAUTH_URL||"http://localhost:3000",x=`${m}/verify-email?token=${d}`,f=`
      <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%); border-radius: 16px; overflow: hidden;">
        <div style="background: linear-gradient(90deg, #10b981 0%, #059669 100%); padding: 30px; text-align: center;">
          <h1 style="color: white; margin: 0; font-size: 28px;">\xa1Bienvenido a Trading Academy!</h1>
        </div>
        <div style="padding: 40px; color: #e2e8f0;">
          <p style="font-size: 18px; margin-bottom: 20px;">Hola <strong style="color: #10b981;">${t}</strong>,</p>
          <p style="font-size: 16px; line-height: 1.6;">Gracias por registrarte en Trading Academy. Est\xe1s a un paso de comenzar tu camino hacia la libertad financiera.</p>
          <p style="font-size: 16px; line-height: 1.6;">Por favor, verifica tu email haciendo clic en el siguiente bot\xf3n:</p>
          <div style="text-align: center; margin: 30px 0;">
            <a href="${x}" style="background: linear-gradient(90deg, #10b981 0%, #059669 100%); color: white; padding: 16px 40px; text-decoration: none; border-radius: 8px; font-weight: bold; font-size: 16px; display: inline-block;">Verificar Email</a>
          </div>
          <div style="background: rgba(16, 185, 129, 0.1); border-left: 4px solid #10b981; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <p style="margin: 0; color: #fbbf24;"><strong>📱 Tu contrase\xf1a ser\xe1 enviada por WhatsApp</strong></p>
            <p style="margin: 10px 0 0; font-size: 14px;">Una vez verificado tu email, recibir\xe1s tu contrase\xf1a de acceso al n\xfamero: <strong>${i}</strong></p>
          </div>
          <p style="font-size: 14px; color: #94a3b8;">Este enlace expira en 24 horas. Si no solicitaste esta cuenta, ignora este mensaje.</p>
        </div>
        <div style="background: #0f172a; padding: 20px; text-align: center; border-top: 1px solid #334155;">
          <p style="color: #64748b; font-size: 12px; margin: 0;">\xa9 2026 Trading Academy - Tu camino hacia la libertad financiera</p>
        </div>
      </div>
    `;try{await fetch("https://apps.abacus.ai/api/sendNotificationEmail",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({deployment_token:process.env.ABACUSAI_API_KEY,app_id:process.env.WEB_APP_ID,notification_id:process.env.NOTIF_ID_VERIFICACIN_DE_EMAIL,subject:"Verifica tu email - Trading Academy",body:f,is_html:!0,recipient_email:a.toLowerCase(),sender_email:`noreply@${new URL(m).hostname}`,sender_alias:"Trading Academy"})})}catch(e){console.error("Error sending verification email:",e)}return s.NextResponse.json({success:!0,message:"Registro exitoso. Revisa tu email para verificar tu cuenta.",userId:g.id,tempPassword:n})}catch(e){return console.error("Signup error:",e),s.NextResponse.json({error:"Error al crear la cuenta. Intenta nuevamente."},{status:500})}}let x=new i.AppRouteRouteModule({definition:{kind:n.x.APP_ROUTE,page:"/api/signup/route",pathname:"/api/signup",filename:"route",bundlePath:"app/api/signup/route"},resolvedPagePath:"/home/ubuntu/academy/Base de datos Academy/trading_academy CJ/trading_academy/nextjs_space/app/api/signup/route.ts",nextConfigOutput:"",userland:r}),{requestAsyncStorage:f,staticGenerationAsyncStorage:h,serverHooks:y}=x,b="/api/signup/route";function v(){return(0,o.patchFetch)({serverHooks:y,staticGenerationAsyncStorage:h})}},52663:(e,a,t)=>{t.d(a,{_:()=>i});let r=require("@prisma/client"),i=globalThis.prisma??new r.PrismaClient}};var a=require("../../../webpack-runtime.js");a.C(e);var t=e=>a(a.s=e),r=a.X(0,[9276,2776,5972],()=>t(65701));module.exports=r})();